### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by luandro** [inxilpro/react-redux-isomorphic-hot-boilerplate#1]
Just cloned, did a fresh `npm install` and ran `npm start`. Get this error: 

```
> NODE_PATH=. PORT=3000 NODE_ENV=development node server/server.js

/Users/luandropvieira/Sites/Clones/react-redux-isomorphic-hot-boilerplate/server/server.js:15
const path = require('path');
^^^^^
SyntaxError: Use of const in strict mode.
```

**Comment by inxilpro** [comment]
You need Node 4.0 or later to use constants.  I could probably update the project to be a little more forgiving…

**Comment by luandro** [comment]
Just a heads up on the README would suffice.

**Comment by luandro** [comment]
This is the only good example of isomorphism working with react-transform, it's worth maintaining.

And keeping it as simple as possible.

**Comment by inxilpro** [comment]
Added a comment to the readme and also added an `engines` section to the `package.json` file.
