### ISSUE TITLE
Consider renaming from isomorphic to universal

### ISSUE THREAD

**Issue by moljac024** [inxilpro/react-redux-isomorphic-hot-boilerplate#2]
Seeing as how a lot of other projects are renaming to universal as it's a better term.

https://medium.com/@mjackson/universal-javascript-4761051b7ae9

**Comment by inxilpro** [comment]
I'm on the fence on this one—while I agree with the underlying argument, the term "universal" is, well, so universal that it makes it difficult to seek out, while "isomorphic" is a term that has come to mean just one thing. If someone's looking for boilerplate for an isomorphic/universal react/redux app, I'm not sure which term they're more likely to search for…

Anyone else have thoughts here?
